name: 'Custom Action Demo'
description: 'Quick demo of custom github action'
inputs:
  doc:
    description: "Document to Reference"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.doc }}