name: 'Custom Action Demo'
description: 'Quick demo of custom github action'
inputs:
  doc:
    description: "Document to Reference"
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "Hello Composite Action. Doc is ${{ inputs.doc }}"
      shell: bash