name: "Run Custom Actions"
on:
  # Used for manually triggering jobs
  workflow_dispatch:
  # Run on changes
  push:

jobs:
  custom-actions-job:
    runs-on: ubuntu-latest
    name: Generate video files
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Custom Container Action
      uses: ./container
      with:
        doc: "README.md"